### ISSUE TITLE
Pokedex stuck on Koffing

### ISSUE THREAD

**Issue by mickeyboxell** [mackorone/tidbyt-pokedex#3]
I have pokedex.webp running on my tidbyt. Since rendering the pokedex.star restricts the display to one non-rotating Pokemon I would like choose which Pokemon to pin. Is there any way do to so?

**Comment by mackorone** [comment]
I haven't played around with publishing apps yet because support is still pretty limited: https://discuss.tidbyt.com/t/publishing-apps/982/41. It's a tad disappointing to hear that the Pokemon doesn't rotate by default. For now I think the best you can do is override the `id_` variable here: https://github.com/mackorone/tidbyt-pokedex/blob/main/pokedex.star#L11

**Comment by mickeyboxell** [comment]
Thanks for the quick follow up. I'll try overriding the id variable.
